#!/bin/bash

# Editors
alias e="vim"

# Re-source my dots
alias re-source="source $HOME/.merc"

# Packages
alias au="sudo apt-get update"
alias au+="sudo apt-get upgrade"
alias ai="sudo apt-get install"
alias ar="sudo apt-get remove"
alias ar-="sudo apt-get purge"
alias apts="apt-cache search"

# Login helpers
## ssh as my user
alias s="ssh -l aditya.ba"
## ssh using automatic password typing
alias st="sshpass"
## ssh without using Public Key auth
alias ssh-no-pk="ssh -o PubkeyAuthentication=no"

# Misc.
## Run last command with sudo privilege (only zsh compatible)
alias suhistory='history | tail -1 | cut -d\   -f4-'
alias wanip='dig +short myip.opendns.com @resolver1.opendns.com'

## Homeshick utils
alias hs="homeshick"
## Vim: Vundle - Silently install bundles
alias vundle-install="vim +BundleInstall +qall"

## Copy and paste (originally Mac commands)
alias lcopy='xsel --clipboard --input'
alias lpaste='xsel --clipboard --output'

# Tmux aliases
alias tmux='tmux -u'
alias ts='tmux new-session -s'
alias ta='tmux attach'
alias tas='tmux attach -t'
alias tl='tmux list-sessions'

# Academics
alias def='dict -d wn'
alias thrus='dict -d moby-thesaurus'
