#!/bin/bash

# Editors
alias e="vim"
alias v="gvim"

# Re-source my dots (only for bash/zsh)
# This alias is over-written in config of fish shell.
alias re-source="source $HOME/.merc"

# Packages
alias au="sudo apt-get update"
alias au+="sudo apt-get upgrade"
alias ai="sudo apt-get install"
alias ar="sudo apt-get remove"
alias ar-="sudo apt-get purge"
alias apts="apt-cache search"

# Login helpers
## ssh as my user
alias s="ssh -l aditya.ba"
## ssh using automatic password typing
alias st="sshpass"
## ssh without using Public Key auth
alias ssh-no-pk="ssh -o PubkeyAuthentication=no"

# Tmux aliases
alias tmux='tmux -u'
alias ts='tmux new-session -s'
alias ta='tmux attach'
alias tas='tmux attach -t'
alias tl='tmux list-sessions'

# Academics
alias def='dict -d wn'
alias thrus='dict -d moby-thesaurus'

# Git aliases
alias ga='git add'
alias gp='git push'
alias gl='git pull'
alias gst='git status'
alias gd='git diff'
alias gc='git commit'
alias gsync='git pull --silent --rebase & git push'
alias gg='git grep'

# Docker
# List docker containers
alias dkps="docker ps"
# List docker images
alias dkimg="docker images"
# Delete all stopped containers.
alias dkdelc="docker ps -a | grep 'Exited' | cut -f1 -d\  | xargs --no-run-if-empty docker rm"
# Delete all untagged images.
alias dkdeli="docker images -q -f dangling=true | xargs --no-run-if-empty docker rmi"
# Delete all stopped containers and untagged images.
alias dkdel="dkc; dki"

# Network
alias wanip='dig +short myip.opendns.com @resolver1.opendns.com'
alias d='dig +noall +answer'
alias dr='dig +noall +answer -x'

# Todo.txt
alias t="todo-txt -t"
alias tgui="gtk-launch todour 2>/dev/null"

# Misc.
alias p="playwire.py"
## Run last command with sudo privilege (only zsh compatible)
alias suhistory='history | tail -1 | cut -d\   -f4-'
## Get cpu frequency
alias mecpu="watch -n1 'cat /proc/cpuinfo | grep -i hz'"

## Homeshick utils
alias hs="homeshick"
## Vim: Vundle - Silently install bundles
alias vundle-install="vim +BundleInstall +qall"

## Copy and paste (originally Mac commands)
alias lcopy='xsel --clipboard --input'
alias lpaste='xsel --clipboard --output'

