#!/bin/bash

# Editors
alias e="vim"

# Login helpers
## ssh as my user
alias s="ssh -l aditya.ba"
## ssh using automatic password typing
alias st="sshpass"
## ssh without using Public Key auth
alias ssh-no-pk="ssh -o PubkeyAuthentication=no"

# Misc.
alias fuck='history | tail -1 | cut -d\   -f4-'
alias mypublicip='dig +short myip.opendns.com @resolver1.opendns.com'

# Copy and paste (originally Mac commands)
alias lcopy='xsel --clipboard --input'
alias lpaste='xsel --clipboard --output'

# Tmux aliases
alias tmux='tmux -u'
alias ts='tmux new-session -s'
alias ta='tmux attach'
alias tas='tmux attach -t'
alias tl='tmux list-sessions'
