#!/bin/bash
# Date of creation: 1-Aug-2014, 8:05 PM
# Author: mitthu
# Job:
# ---
# Common library-like header for my bash scripts

ME="$HOME/.me"
source "$ME/alias"

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
fi

function linux {
	if [[ $platform == 'linux' ]]; then
		eval '$*'
	fi
}

function unset_me {
	unset platform
	unset unamestr
	unset -f linux
	unset -f unset_me
}

function print_colors {
	for i in {0..255} ; do
    printf "\x1b[38;5;${i}mcolour${i}\n"
	done
}

# Pronounce word using phonetics
function defp {
	# espeak for the pronunciation audible output and phonetic alphabet string
	echo "Phoneme mnemonics: $(espeak -ven-uk-rp -x -s 120 "$1" 2> /dev/null)"
	# dict - the client for the dictionary server
	def "$1"
}
