#!/bin/bash
# Created on: 17-Feb-2015, 06:29 pm IST
# Added by:   mitthu (Aditya Basu)
# ----
# Use:
# - Set the bash prompt to show time taken by last command.
# Source:
# http://stackoverflow.com/questions/1862510/how-can-the-last-commands-wall-time-be-put-in-the-bash-prompt

function timer_start {
  timer=${timer:-$SECONDS}
}

function timer_stop {
  timer_show=$(($SECONDS - $timer))
  unset timer
}

trap 'timer_start' DEBUG
PROMPT_COMMAND=timer_stop

PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w [${timer_show}s]\$ '
