.TH myip 1 "Last update: June 25, 2018" "mitthu" "mitthu's Manual"

.SH NAME
myip \- get list of ip addresses

.SH SYNOPSIS
.B myip
[
.BR --all " | " --internal " | " --external
]

.SH DESCRIPTION
Lookup allocated ip addresses on relevant interfaces.

.IR Note :
On Linux the IPs are prefixes with the interface (for example:
.BR "'lo:127.0.0.1'" ),
while on Mac OS X IPs are suffixed with a colon (for example:
.BR "'127.0.0.1:'" ).

.SH OPTIONS
.TP
.BR --all " or " all
list all IPs, new line separated

.TP
.BR --allspaced " or " allspaced
list all IPs, space separated

.TP
.BR --all-nolocal " or " all-nolocal
same as
.B all
, execpt don't list interface
.I lo

.TP
.BR --allspaced-nolocal " or " allspaced-nolocal
same as
.B allspaced
, execpt don't list interface
.I lo

.TP
.BR --internal " or " internal
list all internal IPs, new line seperated

.TP
.BR --external " or " external
list all external IPs, new line seperated

.TP
.BR -h " or " --help " or " help
show help.

.SH EXAMPLES
.nf
.B $ myip
eth0:10.118.50.89
eth1:172.20.1.5
lo:127.0.0.1

.B $ myip --allspaced
eth0:10.118.50.89 eth1:172.20.1.5 lo:127.0.0.1

.B $ myip --internal
eth0:10.118.50.89 eth1:172.20.1.5

.fi

.SH AUTHOR
Aditya Basu <me@adityabasu.me> (aka. mitthu).

.SH "SEE ALSO"
dotfiles(7)
