.TH myos 1 "Last update: June 25, 2018" "mitthu" "mitthu's Manual"

.SH NAME
myos \- describe the host OS

.SH SYNOPSIS
.B myos
[
.BR -p " | " -d
]

.B myos
[
.BR --os " | " --distro
]

.SH DESCRIPTION
The script determines the host OS.

.SH OPTIONS
.TP
.BR -p " or " --os " or " --platform
print the OS type. The script recognizes the following OS:
.RS
.IP \[bu] 4
linux
.IP \[bu]
unix
.IP \[bu]
solaris
.IP \[bu]
macosx
.IP \[bu]
windows
.IP \[bu]
unknown
.RE

.TP
.BR -d " or " --distro
print the distro. The script recognizes the following distros:
.RS
.IP \[bu] 4
os:linux
.RS
.IP - 4
slackware
.IP -
debian
.IP -
centos
.IP -
raspberry-pi
.RE

.IP \[bu] 4
os:windows
.RS
.IP - 4
cygwin
.IP -
msys
.RE

.IP \[bu] 4
os:unix
.RS
.IP - 4
bsd
.IP -
freebsd
.RE

.IP \[bu] 4
unknown
.RE

.TP
.BR -h " or " --help
show help.


.SH EXAMPLES
.I myos


.SH FILES
.I /etc/issue\p
.I /etc/slackware-version\p

\# --------------------------------------------------------------------------------
.SH AUTHOR
Aditya Basu <me@adityabasu.me> (aka. mitthu).

.SH "SEE ALSO"
dotfiles(7)
