.TH myupdate 7 "Last update: July 9, 2018" "mitthu" "mitthu's Manual"
.mso www.tmac

.SH NAME
myupdate \- update dotfiles

.SH SYNOPSIS
.B myupdate

.SH DESCRIPTION
Update dotfiles repository and link new changes. Also setup a cron job which
runs this binary every
.BR "10mins" .
On every run the output is logged to
.IR /tmp/melog/myupdate .
The script also updates man page cache, runs
.BR fish_update_completions .

.SS cron Entry
.nf
*/10 * * * * ~/.me/bin/myupdate
.fi

.SH EXAMPLES
.nf
.B "$ myupdate"
.fi

.SH AUTHOR
Aditya Basu <me@adityabasu.me> (aka. mitthu).

.SH "SEE ALSO"
dotfiles(7)
