.TH template 7 "Last update: June 25, 2018" "mitthu" "mitthu's Manual"
.mso www.tmac

.SH NAME
template \- brief description

.SH SYNOPSIS
\fBtemplate\fP [\fB-h\fP] [\fB-t\fP \fItype\fP] \fIfilename\fP ...

.SH DESCRIPTION
Describe the awesome tool.

\fINote\fP: that this is an example man page. This man page does not correspond
to any utility named template.

.SH OPTIONS
.TP
.BR -e " or " --enable
enable syntax highlighting

.TP
.B -d
disable syntax highlighting

.TP
.BI -f " filename"
Specifies the file you want to edit. This option must be given with the
.BR " -e " "or the " "-d " option.

.TP
.B -h
show help

.SH FILES
.I /etc/foorc
.RS
Global system wide configuration file.
.RE

.I $HOME/.foorc
.RS
Local system configuration file.
.RE

.SH EXAMPLES
.nf
.B "$ template"
linux raspberry-pi

.B "$ template -p"
linux
.fi

.SH AUTHOR
Aditya Basu <me@adityabasu.me> (aka. mitthu).

.SH "SEE ALSO"
dotfiles(7)
